on:
  push:
    branches: [main]
  release:
    types: [created]

env:
  NODE_VERSION: '12.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Deploy To Azure
      uses: thetre97/azure-deploy@master
      with:
        connection-string: ${{ secrets.AZURE_CONNECTION_STRING }}
        container-name: ${{ secrets.AZURE_CONTAINER_STARTERS }}
